// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace Isochrone
{
    public class IsochroneOutputs: SystemResults
    {
		/// <summary>
		/// number of rhino lines
		/// </summary>
		[JsonProperty("linecount")]
		public double Linecount {get; set;}

		/// <summary>
		/// report function progress
		/// </summary>
		[JsonProperty("report")]
		public string Report {get; set;}



        /// <summary>
        /// Construct a IsochroneOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public IsochroneOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a IsochroneOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public IsochroneOutputs(double linecount, string report): base()
        {
			this.Linecount = linecount;
			this.Report = report;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}